name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet & Bye user
        run: |
          echo "Welcome Kishore"
          echo "Bye Kishore"
      
  
